version: "3.9"
services:
  db:
    image: "postgres:13"
    ports:
      - "5432:5432"
    env_file:
      - keys
    volumes:
      - ./data:/usr/app/data
      - ./import.sql:/docker-entrypoint-initdb.d/01-import.sql
