#!/bin/bash
# This script will automatically generate schemas using csvsql from the csv files in the data folder

echo "Clearing old tables..."
echo "" > ./import.sql

echo "Generating Tables..."
for file in data/*; do

  echo "${file} processing..."

  filename=$(basename "${file}")
  filename_no_extension="${filename%%.*}"

  sql_table_name=$(echo "$filename_no_extension" | awk '{ print tolower($0); }')

  if [ ! "$sql_table_name" = "${filename_no_extension}" ]; then
    mv "$file" "./data/${sql_table_name}.csv"
    echo "Renamed ${file} to ${sql_table_name}.csv"
  fi

  csvsql --no-doublequote "./data/$sql_table_name.csv" >> ./import.sql

  echo "COPY ${sql_table_name} FROM '/usr/app/data/$sql_table_name.csv' HEADER csv;" >> ./import.sql
  echo "${filename} done."

done

echo "Done"
